grpc_listener:
  address: 127.0.0.1:9000

amqp:
  address: 127.0.0.1:5672
  queue: auditing_dev

database:
  adapter: MongoDB
  host: localhost
  name: auditing_dev
  port: 27017
  username: auditer
  password: fabulous_rainbows
