version: '3.7'

volumes:
  mongo:

services:
  auditer:
    image: auditer
    build: .
    ports:
      - 9000:9000
    volumes:
      - .:/app/current
    # depends_on:
    #   - mongo

  # mongo:
  #   image: mongo:4.1.11-bionic
  #   ports:
  #     - 27017:27017
  #   volumes:
  #     - mongo:/data/db
  #   environment:
  #     MONGO_INITDB_ROOT_USERNAME: auditer
  #     MONGO_INITDB_ROOT_PASSWORD: fabulous_rainbows
  #     MONGO_INITDB_DATABASE: auditer_dev
